name: PHP Deployment

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP environment (optional, for testing)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Install dependencies (if using Composer)
      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      # Step 4: Deploy via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 41.150.34.16
          username: root
          key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAsOQkV3vTm6jQH67y8l1W/fFsrIz9q2Uf7peL84Om8ZcnQZfxYRff
S2CQaIZiCy829MX61tw4pe7KCgtQvfHGbYgpA4hLBi0EdK8sjIYnZLAqenHaXLKHxMDCBP
G7PFqnRKD9zqe9yHkIVS32TLUTcNPMSWzyXzmPmVXk9NASGgPndOKGd5OwD0L6zYNLRzLR
kpQd4KIpun8eTjYJzqsQnIIGcEMn4MbLJ3Tqs9DMDLe414ylMimiHFiDbHSSHKKukXX//t
BxCHOidTKT/ZWjsQtu3NRAn1gN/fwglT1zCZSvdfyXG/iUQpranI3OVLZA9/ZetYF/JWg7
rX32OlpLD+XdvgrhNA2P73HB1+NlkbYlmZ5w+UfmkcInpithdYu5FV3pT7aQ7mjXYtb+C3
hMlAQM+xVPfVCYpdHBNKSEpjybmzWU8zmk5CE0+orb/WQsLK+ucyTsiCppgmX9T/z4EdgD
TU1qS9WUeEgNW5+tu4ny4M7L1osTfTX/qPRvr0tTAAAFiOncPnjp3D54AAAAB3NzaC1yc2
EAAAGBALDkJFd705uo0B+u8vJdVv3xbKyM/atlH+6Xi/ODpvGXJ0GX8WEX30tgkGiGYgsv
NvTF+tbcOKXuygoLUL3xxm2IKQOISwYtBHSvLIyGJ2SwKnpx2lyyh8TAwgTxuzxap0Sg/c
6nvch5CFUt9ky1E3DTzEls8l85j5lV5PTQEhoD53TihneTsA9C+s2DS0cy0ZKUHeCiKbp/
Hk42Cc6rEJyCBnBDJ+DGyyd06rPQzAy3uNeMpTIpohxYg2x0khyirpF1//7QcQhzonUyk/
2Vo7ELbtzUQJ9YDf38IJU9cwmUr3X8lxv4lEKa2pyNzlS2QPf2XrWBfyVoO6199jpaSw/l
3b4K4TQNj+9xwdfjZZG2JZmecPlH5pHCJ6YrYXWLuRVd6U+2kO5o12LW/gt4TJQEDPsVT3
1QmKXRwTSkhKY8m5s1lPM5pOQhNPqK2/1kLCyvrnMk7IgqaYJl/U/8+BHYA01NakvVlHhI
DVufrbuJ8uDOy9aLE301/6j0b69LUwAAAAMBAAEAAAGBAKzRd5/w3kBJoWwS5FBdWMwovl
+mL37wAU58yMJUcRm+7x9qbuzJAeMGqI82GzuKGUry0apw5PdYYBOIEo5AU/hW+pr04Tdb
a+sD6aYwuvPoGNgfu5Ks6XAUUnm6IY9Jkfm+v7jSsNvXQ4jUqrkuf5vPkNp7kh/ugJjyDg
oP7l90SQEs/up8Y5nFenqmNzmMMKvgAYChbdtCrj0DFnnPLx94+Qlc0u0Lyxb1Zwfeijwy
kmgkhJCJlFPVNjETglxvojWzRwFDGVLompYdoMrQeeYTq2wH3Dg6q9n5LMX3ArGuhFLPvz
yj+ENrrj2fOKi8iiicp724PtJvjVi/ESeo38ojS3yhCEISvzPydFhkVtBtWT3oLkE8wX7I
gd3/MlB9ywXs7zjTRp1ppulua1xBUSn7pGTG52KNyIfTBuLDfYiLhYlCGBSixFzyQTqHDd
ChwiQqbr5xsZfT/MBnwuTzDwaA7UoXrshOe24jm1nPlbEBeDGJzDQ0jT7aWhDke2iZQQAA
AMA2wNJfGzvOsPygXdwBg1PJKuMc+PBL63jVWLyRpsxPNLRNcfemPCuZqMs3h1HZBC1orK
5eccy1T/NkUgbWP7kHAxYEOIh9fisxuHiOjNvUH1Q4gSp8dPdDbB4UOcTK3Jl3aqv2JKT7
GPflP441BP9p7w+3tOh9h+/43HhMtKKjvCUd7vq+zgfhrEmsVcGE/kcXDWDRzhA/76Cht0
beJ9ffOar2NB5VvwG4cUURDok922e6wHMuQ3HyePUx2/hz6gYAAADBANWaJ52GnDlQzfC/
1XjRJRXyzOveGiC85UREgWJrllkv36xrfK8d8T6HA4e8sU6GZlu5fkWbqCG3pu6jwzV24S
/BSCJMzoyLh17Krk53C/IQP/OKJ2pBS3FfNDUPLfMrtSHiYah8UzFyPqnrhznabJTWdDuC
jh7mvqwTMdKI8ESX6XqYvtl3rdWYnjW3MuHXsOjjAu+lFsDCcH7CrPvN2D4oI2CKw7N+oC
rbbmbnzWHt9dR5xBJsTN5JmLDTT23H6wAAAMEA1ACUDka7+t6Enxd5/KFKhb1CMT2CmRAd
l3z27G94cS9CUu4wt8jRJGZLHxABNmaqmD6J35vm7scFJKVqLx4kX7kGZC5CnvSmdAS/BL
Xns9CHGeD/Q/l/LC5tZPuzwiecLHMlHQGIPy1fDiQj4mgZ0HWWcZQEpUIAJPmozhEmpz2c
0lQQFJCG1cOP/BTc2KK/qMLSmNkn5ZxQxCjfyIJmZdTNqi1264OjyoqaEoiSMJtLxQsajM
PyH8fawvl2T1g5AAAAEU5xb2JpbGVzLU5vdGVib29rAQ==
          port: 22
          # Run deployment commands on the remote host. Replace or extend the
          # commands below with the actual deploy steps you need (git pull,
          # composer install, service restart, etc.).
          script: |
            set -e
            echo "Starting deploy on $(hostname)"
            mkdir -p /var/www/html
            # adjust ownership if needed (may fail on some hosts)
            chown -R www-data:www-data /var/www/html || true
            # place a marker file to verify deployment succeeded
            echo "Deployed by GitHub Actions on $(date)" > /var/www/html/DEPLOYED_BY
            ls -la /var/www/html
