name: PHP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 41.150.34.16
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "Starting deploy on $(hostname)"
            mkdir -p /var/www/html
            chown -R www-data:www-data /var/www/html || true
            echo "Deployed by GitHub Actions on $(date)" > /var/www/html/DEPLOYED_BY
            ls -la /var/www/html

